### ISSUE TITLE
How to run example in GUI

### ISSUE THREAD

**Issue by SimonMa2000** [danebjork/AutomatedMBAM#7]
I tried to run the webUI and load modules in ./example, but it does not respond after importing the .json file and .h5 file as model and data.  Are there other parts that need to be fill in?

**Comment by danebjork** [comment]
Are you running the engine with main.py?

**Comment by SimonMa2000** [comment]
Yes, I'm running main.py locally with python 3.6 on Mac in Anaconda channel. 

Seems something went  wrong with MongoDB connection; It's not port 9000 by default.  Do I need to upload data to MongoDB cluster instead?  

The terminal  reports the following logs:
> MongoDB?01/15/2019 10:34:44 AM - MBAM - INFO - Ready for Connection
> 01/15/2019 10:41:10 AM - MBAM - INFO - Getting data
> 01/15/2019 10:41:40 AM - websockets.server - ERROR - Error in connection handler
> Traceback (most recent call last):
>   File "/Users/me/anaconda3/lib/python3.6/site-packages/websockets/server.py", line 169, in handler
>     yield from self.ws_handler(self, path)
>   File "main.py", line 59, in time
>     mbamui.read_model_data(await websocket.recv())
>   File "/Users/me/Desktop/Projects/AutomatedMBAM/mbam/ui.py", line 108, in read_model_data
>     self.data.load_bytes(data_str)
>   File "/Users/me/Desktop/Projects/AutomatedMBAM/mbam/modeling/data.py", line 58, in load_bytes
>     self.load_hdf5(os.path.join(os.getcwd(), "temp.h5"))
>   File "/Users/me/Desktop/Projects/AutomatedMBAM/mbam/modeling/data.py", line 98, in load_hdf5
>     self.save_data()
>   File "/Users/me/Desktop/Projects/AutomatedMBAM/mbam/modeling/data.py", line 64, in save_data
>     self.id = self.mongo.save_model_data(self.data_json)
>   File "/Users/me/Desktop/Projects/AutomatedMBAM/mbam/mongo.py", line 322, in save_model_data
>     return str(self.data.insert_one(data_json).inserted_id)
>   File "/Users/me/anaconda3/lib/python3.6/site-packages/pymongo/collection.py", line 682, in insert_one
>     session=session),
>   File "/Users/me/anaconda3/lib/python3.6/site-packages/pymongo/collection.py", line 598, in _insert
>     bypass_doc_val, session)
>   File "/Users/me/anaconda3/lib/python3.6/site-packages/pymongo/collection.py", line 578, in _insert_one
>     True, _insert_command, session)
>   File "/Users/me/anaconda3/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1098, in _retryable_write
>     with self._tmp_session(session) as s:
>   File "/Users/me/anaconda3/lib/python3.6/contextlib.py", line 81, in __enter__
>     return next(self.gen)
>   File "/Users/me/anaconda3/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1404, in _tmp_session
>     s = self._ensure_session(session)
>   File "/Users/me/anaconda3/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1391, in _ensure_session
>     return self.start_session(causal_consistency=False)
>   File "/Users/me/anaconda3/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1369, in start_session
>     server_session = self._get_server_session()
>   File "/Users/me/anaconda3/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1377, in _get_server_session
>     return self._topology.get_server_session()
>   File "/Users/me/anaconda3/lib/python3.6/site-packages/pymongo/topology.py", line 416, in get_server_session
>     None)
>   File "/Users/me/anaconda3/lib/python3.6/site-packages/pymongo/topology.py", line 199, in _select_servers_loop
>     self._error_message(selector))
> pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused
